Repository EzZarGG/MLBB, pull requests merged in 2025-05, with the labels that each got.

#46 Reorganize solution architecture and extract Logger to DLL
  EasySave/EasySave.sln
  EasySave/EasySaveV1/Config.cs
  EasySave/EasySaveV1/EasySaveConsole/Controllers/BackupController.cs
  EasySave/EasySaveV1/EasySaveConsole/Managers/BackupManager.cs
  EasySave/EasySaveV1/EasySaveConsole/Models/Backup.cs
  EasySave/EasySaveV1/EasySaveConsole/Models/StateModel.cs
  EasySave/EasySaveV1/EasySaveConsole/Views/BackupView.cs
  EasySave/EasySaveV1/EasySaveV1.csproj
  EasySave/EasySaveV1/Program.cs
  EasySaveLogging/EasySaveLogging.csproj
  EasySaveLogging/Logger.cs
Labels: version 1.1

#50 Docs: Add EasySaveLogging DLL Documentation
  DLL_Documentation.md
Labels: version 1.0

#52 28 add support for json xml log file format
  EasySave/EasySaveV1/Config.cs
  EasySave/EasySaveV1/EasySaveConsole/Controllers/BackupController.cs
  EasySave/EasySaveV1/EasySaveConsole/Views/BackupView.cs
  EasySave/EasySaveV1/Program.cs
  EasySaveLogging/Logger.cs
Labels: version 1.1

#55 54 create dll documentation for v11
  Docs/DLL_Documentation.md
Labels: version 1.1

#57 30 update documentation for log format selection
  Docs/UserGuide.md
Labels: version 1.1

#60 docs: update README with global overview and v1.1.0 details
  README.md
Labels: documentation, version 1.1

#61 update: Update .gitattributes to exclude EasySaveV1 from release arch…
  .gitattributes
Labels: version 1.1

#64 doc: update activity and sequence diagram to fit with the v1.1
  UMLDiagram/UML diagram - EasySave - activity diagram.drawio.png
  UMLDiagram/UML diagram - EasySave - sequence diagram.drawio.png
  UMLDiagram/diagramme UML - EasySave - activity diagram.png
  UMLDiagram/diagramme UML - EasySave - sequence diagram.png
Labels: version 1.1

#68 - create a workflow to create release source code
  .github/workflows/create-release-zip.yml
Labels: version 1.1

#72 delete workflow
  .github/workflows/create-release-zip.yml
Labels: version 1.1

#76 feat: Set up application structure and internationalization framework
  EasySave/EasySave.sln
  EasySave/EasySaveV2.0/Config.cs
  EasySave/EasySaveV2.0/Controllers/BackupController.cs
  EasySave/EasySaveV2.0/Controllers/LogController.cs
  EasySave/EasySaveV2.0/Controllers/SettingsController.cs
  EasySave/EasySaveV2.0/EasySaveV2.0.csproj
  EasySave/EasySaveV2.0/MainForm.Designer.cs
  EasySave/EasySaveV2.0/MainForm.cs
  EasySave/EasySaveV2.0/MainForm.resx
  EasySave/EasySaveV2.0/Managers/BackupManager.cs
  EasySave/EasySaveV2.0/Managers/LanguageManager.cs
  EasySave/EasySaveV2.0/Models/Backup.cs
  EasySave/EasySaveV2.0/Models/EncryptionProgressEventArgs.cs
  EasySave/EasySaveV2.0/Models/FileProgressEventArgs.cs
  EasySave/EasySaveV2.0/Models/StateModel.cs
  EasySave/EasySaveV2.0/Program.cs
  EasySave/EasySaveV2.0/Ressources/translation.json
  EasySave/EasySaveV2.0/Views/BackupForm.Designer.cs
  EasySave/EasySaveV2.0/Views/BackupForm.cs
  EasySave/EasySaveV2.0/Views/BackupForm.resx
  EasySave/EasySaveV2.0/Views/LanguageSelectionForm.cs
  EasySave/EasySaveV2.0/Views/LanguageSelectionForm.resx
  EasySave/EasySaveV2.0/Views/SettingsForm.Designer.cs
  EasySave/EasySaveV2.0/Views/SettingsForm.cs
  EasySave/EasySaveV2.0/Views/SettingsForm.resx
Labels: version 2.0

#85 doc: modify the class, squence and activity diagram for the v2.0
  UMLDiagram/UML diagram - EasySave - activity diagram.png
  UMLDiagram/UML diagram - EasySave - class diagram.png
  UMLDiagram/UML diagram - EasySave - class diagram.png.png
  UMLDiagram/UML diagram - EasySave - sequence diagram.png
Labels: documentation, version 2.0

#86 77 implement backup management functionality
  EasySave/EasySaveV2.0/Controllers/BackupController.cs
  EasySave/EasySaveV2.0/Controllers/LogController.cs
  EasySave/EasySaveV2.0/Controllers/SettingsController.cs
  EasySave/EasySaveV2.0/EasySaveV2.0.csproj
  EasySave/EasySaveV2.0/MainForm.cs
  EasySave/EasySaveV2.0/Managers/BackupManager.cs
  EasySave/EasySaveV2.0/Managers/LanguageManager.cs
  EasySave/EasySaveV2.0/Models/EncryptionProgressEventArgs.cs
  EasySave/EasySaveV2.0/Models/FileProgressEventArgs.cs
  EasySave/EasySaveV2.0/Program.cs
  EasySave/EasySaveV2.0/Views/BackupForm.cs
  EasySave/EasySaveV2.0/Views/SettingsForm.Designer.cs
  EasySave/EasySaveV2.0/Views/SettingsForm.cs
Labels: bug, version 2.0

#87 Enable the creation, update, delete and run of backups.
  EasySave/EasySaveV2.0/MainForm.cs
Labels: version 2.0

#89 78 implement language management system
  EasySave/EasySaveV2.0/MainForm.cs
  EasySave/EasySaveV2.0/Managers/LanguageManager.cs
  EasySave/EasySaveV2.0/Ressources/translation.json
  EasySave/EasySaveV2.0/Views/BackupForm.Designer.cs
  EasySave/EasySaveV2.0/Views/BackupForm.cs
  EasySave/EasySaveV2.0/Views/BackupForm.resx
  EasySave/EasySaveV2.0/Views/LanguageSelectionForm.cs
  EasySave/EasySaveV2.0/Views/LanguageSelectionForm.resx
  EasySave/EasySaveV2.0/Views/SettingsForm.cs
Labels: version 2.0

#90 35.2 integrate cryptosoft for file encryption
  EasySave/CryptoConsole/App.config
  EasySave/CryptoConsole/CryptoConsole.csproj
  EasySave/CryptoConsole/Program.cs
  EasySave/CryptoLibrary/CryptoLibrary.csproj
  EasySave/CryptoLibrary/CryptoManager.cs
  EasySave/EasySave.sln
  EasySave/EasySaveV1/App.config
  EasySave/EasySaveV1/EasySaveConsole/Managers/CryptoManager.cs
  EasySave/EasySaveV2.0/Config.cs
  EasySave/EasySaveV2.0/Controllers/BackupController.cs
  EasySave/EasySaveV2.0/Controllers/LogController.cs
  EasySave/EasySaveV2.0/Controllers/SettingsController.cs
  EasySave/EasySaveV2.0/EasySaveV2.0.csproj
  EasySave/EasySaveV2.0/Managers/BackupManager.cs
  EasySave/EasySaveV2.0/Models/FileProgressEventArgs.cs
  EasySave/EasySaveV2.0/Views/SettingsForm.cs
  EasySave/EasySaveV2.0/appsetting.json
  EasySaveLogging/Logger.cs
Labels: version 2.0

#91 34 implement windows forms UI components -> dev
  .vscode/launch.json
  EasySave/EasySaveV2.0/Controllers/BackupController.cs
  EasySave/EasySaveV2.0/Controllers/LogController.cs
  EasySave/EasySaveV2.0/Controllers/SettingsController.cs
  EasySave/EasySaveV2.0/MainForm.Designer.cs
  EasySave/EasySaveV2.0/MainForm.cs
  EasySave/EasySaveV2.0/Managers/BackupManager.cs
  EasySave/EasySaveV2.0/Managers/LanguageManager.cs
  EasySave/EasySaveV2.0/Models/Backup.cs
  EasySave/EasySaveV2.0/Models/FileProgressEventArgs.cs
  EasySave/EasySaveV2.0/Views/BackupForm.Designer.cs
  EasySave/EasySaveV2.0/Views/BackupForm.cs
  EasySave/EasySaveV2.0/Views/LanguageSelectionForm.Designer.cs
  EasySave/EasySaveV2.0/Views/LanguageSelectionForm.cs
  EasySave/EasySaveV2.0/Views/SettingsForm.Designer.cs
  EasySave/EasySaveV2.0/Views/SettingsForm.cs
Labels: version 2.0

#106 Implement CryptoSoft Integration for File Encryption
  EasySave/CryptoConsole/CryptoConsole.csproj
  EasySave/EasySaveV2.0/Config.cs
  EasySave/EasySaveV2.0/Controllers/SettingsController.cs
  EasySave/EasySaveV2.0/EasySaveV2.0.csproj
  EasySave/EasySaveV2.0/MainForm.cs
  EasySave/EasySaveV2.0/Managers/BackupManager.cs
  EasySave/EasySaveV2.0/Views/SettingsForm.cs
  EasySave/EasySaveV2.0/appsetting.json
Labels: version 2.0

#109 Update README and DLL documentation for EasySave v2.0.0
  Docs/DLL_Documentation.md
  Docs/UserGuideV2.md
  README.md
Labels: documentation, version 2.0

#114 modify UML diagram :
  UMLDiagram/UML diagram - EasySave - activity diagram.png
  UMLDiagram/UML diagram - EasySave - class diagram.png
  UMLDiagram/UML diagram - EasySave - sequence diagram.png
Labels: documentation, version 2.0

#115 Enhance BackupManager logging and error handling
  EasySave/EasySaveV2.0/Managers/BackupManager.cs
Labels: version 2.0

#118 Add EasySave V3.0 project to solution
  EasySave/EasySave.sln
  EasySave/EasySaveV3.0/Config.cs
  EasySave/EasySaveV3.0/Controllers/BackupController.cs
  EasySave/EasySaveV3.0/Controllers/LogController.cs
  EasySave/EasySaveV3.0/Controllers/SettingsController.cs
  EasySave/EasySaveV3.0/EasySaveV3.0.csproj
  EasySave/EasySaveV3.0/MainForm.Designer.cs
  EasySave/EasySaveV3.0/MainForm.cs
  EasySave/EasySaveV3.0/MainForm.resx
  EasySave/EasySaveV3.0/Managers/BackupManager.cs
  EasySave/EasySaveV3.0/Managers/LanguageManager.cs
  EasySave/EasySaveV3.0/Models/Backup.cs
  EasySave/EasySaveV3.0/Models/EncryptionKey.cs
  EasySave/EasySaveV3.0/Models/EncryptionProgressEventArgs.cs
  EasySave/EasySaveV3.0/Models/FileProgressEventArgs.cs
  EasySave/EasySaveV3.0/Models/LogLevel.cs
  EasySave/EasySaveV3.0/Models/StateModel.cs
  EasySave/EasySaveV3.0/Program.cs
  EasySave/EasySaveV3.0/Resources/translations.json
  EasySave/EasySaveV3.0/Views/BackupForm.Designer.cs
  EasySave/EasySaveV3.0/Views/BackupForm.cs
  EasySave/EasySaveV3.0/Views/BackupForm.resx
  EasySave/EasySaveV3.0/Views/LanguageSelectionForm.Designer.cs
  EasySave/EasySaveV3.0/Views/LanguageSelectionForm.cs
  EasySave/EasySaveV3.0/Views/LanguageSelectionForm.resx
  EasySave/EasySaveV3.0/Views/LogViewerForm.cs
  EasySave/EasySaveV3.0/Views/SettingsForm.Designer.cs
  EasySave/EasySaveV3.0/Views/SettingsForm.cs
  EasySave/EasySaveV3.0/Views/SettingsForm.resx
  EasySave/EasySaveV3.0/appsetting.json
Labels: version 3.0

#119 98 implement priority file management
  EasySave/EasySaveV3.0/Config.cs
  EasySave/EasySaveV3.0/Controllers/BackupController.cs
  EasySave/EasySaveV3.0/Controllers/LogController.cs
  EasySave/EasySaveV3.0/Controllers/SettingsController.cs
  EasySave/EasySaveV3.0/MainForm.cs
  EasySave/EasySaveV3.0/Managers/BackupManager.cs
  EasySave/EasySaveV3.0/Models/StateModel.cs
  EasySave/EasySaveV3.0/appsetting.json
Labels: version 3.0

#120 99 block concurrent transfer of large files
  EasySave/EasySaveV3.0/Controllers/SettingsController.cs
  EasySave/EasySaveV3.0/Managers/BackupManager.cs
  EasySave/EasySaveV3.0/Resources/translations.json
  EasySave/EasySaveV3.0/Views/SettingsForm.Designer.cs
  EasySave/EasySaveV3.0/Views/SettingsForm.cs
Labels: version 3.0

#121 Implementing cryptosoft mono-instance for v3
  EasySave/EasySaveV3.0/Controllers/BackupController.cs
  EasySave/EasySaveV3.0/MainForm.Designer.cs
  EasySave/EasySaveV3.0/MainForm.cs
Labels: version 3.0

#123 Mutex corrigé
  EasySave/CryptoConsole/Program.cs
  EasySave/EasySaveV3.0/Controllers/BackupController.cs
Labels: documentation, version 3.0
